/*  =========================================================================
    agent_smtp_classes - private header file

    Copyright (C) 2014 - 2015 Eaton                                        
                                                                           
    This program is free software; you can redistribute it and/or modify   
    it under the terms of the GNU General Public License as published by   
    the Free Software Foundation; either version 2 of the License, or      
    (at your option) any later version.                                    
                                                                           
    This program is distributed in the hope that it will be useful,        
    but WITHOUT ANY WARRANTY; without even the implied warranty of         
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          
    GNU General Public License for more details.                           
                                                                           
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef AGENT_SMTP_CLASSES_H_INCLUDED
#define AGENT_SMTP_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/agent_smtp.h"

//  Internal API
#include "emailconfiguration.h"
#include "email.h"
#include "subprocess.h"
#include "bios_smtp_server.h"

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_SMTP_EXPORT void
    emailconfiguration_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_SMTP_EXPORT void
    email_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_SMTP_EXPORT void
    subprocess_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_SMTP_EXPORT void
    bios_smtp_server_test (bool verbose);

#endif
